import React from "react";
import photo from "../../asset/One.jpg";
import "./Menudown.css";
function Menudown() {
  return (
    <div className="container conatiner1">
      <div className="row menudownrow2">
        <div
          className="col-lg-4"
          style={{
            display: "flex",
            alignSelf: "center",
          }}
        >
          <img src={photo} className="menudownimage" />
        </div>
        <div className="col-lg-7 mx-lg-4 ">
          <h1 className="menudownh1">
            <b>SYAC</b>
          </h1>
          <p className="menudownp">
            <b>
              SYAC only accepts young apes spoiled by Bored Dads and Desperate
              Moms. Inspired by the TV show “Growing Pains”, these apes are all
              growing pains. These 10,000 unique young apes are looking for ways
              to entertain themselves by causing trouble.{" "}
            </b>
          </p>
          <p className="menudownp">
            <b>
              SYAC is an NFT collection consisting of young apes with over 200
              accessories, expressions and clothing generated by an algorithm.
              We are the first NFT Collection in the world that has Mining
              Utility to benefit our members in a sustainable way.
            </b>
          </p>
        </div>
      </div>
    </div>
  );
}

export default Menudown;
