export const accordionData = [
  {
    title: "WHAT IS THE SYAC PROJECT?",
    content: `SYAC is an NFT collection consisting of young apes with over 200 accessories, expressions and clothing generated by an algorithm. We are the first NFT Collection in the world that has Mining Utility to benefit our members in a sustainable way. Ethereum blockchain. ERC-721
    `,
  },
  {
    title: "WHAT WILL BE THE MINT PRICE?",
    content: `Our young apes will be listed at 0.08ETH per mint`,
  },
  {
    title: "WHAT’S THE TOTAL NUMBER AVAILABLE TO MINT?",
    content: `10,000`,
  },
  {
    title: "WHAT IS THE MINT DATE?",
    content: `Pre-sale December 11th. 16:00 UTC mint window 24hrs.<br/>
             Limit for Presale: 2 NFT per wallet
             Public Sale December 12th. 16:00 UTC 
             Limit for Public Sale: 10NFT Per wallet`,
  },
  {
    title: "WHO IS ELIGIBLE FOR THE PRE-SALE?",
    content: `All whitelisted`,
  },
  {
    title: "WHEN IS THE REVEAL DATE?",
    content: `After public sale`,
  },
  {
    title: "HOW MANY SYAC CAN I MINT?",
    content: `Limit for Pre-Sale: 2 NFT per wallet 
    Limit for Public Sale: 10 NFT per wallet `,
  },
];
