import React from "react";
import "./Headerdown.css";
function Headerdown() {
  return (
    <div className="container conatiner13">
      <div className="row headerdownrow">
        <div className="col-11">
          <h2 className="headerdownh2">
            <b>SYAC</b>
          </h2>
          <p className="headerdownp">
            <b>
              SYAC only accepts young apes spoiled by Bored Dads and Desperate
              Moms. Inspired by the TV show “Growing Pains”, these apes are all
              growing pains. These 10,000 unique young apes are looking for ways
              to entertain themselves by causing trouble. SYAC is an NFT
              collection consisting of young apes with over 200 accessories,
              expressions and clothing generated by an algorithm. We are the
              first NFT Collection in the world that has Mining Utility to
              benefit our members in a sustainable way.
            </b>
          </p>
        </div>
      </div>
    </div>
  );
}

export default Headerdown;
